### ISSUE TITLE
Android release didn't work fine

### ISSUE THREAD

**Issue by done134** [superandrew213/react-native-charting#4]
**Is work for dev mode, but not work in release apk 
This is my Option：**

`    getOption() { 
let companyName = [];
        let companyRatio = [];
        this.state.insuranceArray.forEach(function (item, index, array) {
            companyName.push(item.insuranceName);
            companyRatio.push(item.pre);
        });
        return {

            backgroundColor: '#191919',
            tooltip: {
                trigger: 'axis',
                axisPointer: {           
                    type: 'shadow'       
                }
            },

            animation: false,
            /*legend: {
                orient: 'vertical',
                data: companyName
            },*/
            lineStyle: {
                color: '#48b',
                width: 2,
                type: 'solid'
            },
            textStyle: {
                color: '#fff'
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: [
                {
                    type: 'category',
                    data: companyName,
                    axisTick: {
                        alignWithLabel: true
                    },
                    axisLabel: {
                        textStyle: {
                            color: '#fff'
                        },

                    },
                    axisLine: {
                        lineStyle: {
                            color: 'white',
                        }
                    },
                }
            ],
            yAxis: [
                {
                    type: 'value',
                    axisLabel: {
                        show: true,
                        interval: 'auto',
                        formatter: '{value} %',
                        textStyle: {
                            color: '#fff'
                        },

                    },
                    axisLine: {
                        lineStyle: {
                            color: 'white',
                        }
                    },
                    show: true
                }
            ],
            series: [
                {
                    name: 'Number of clues',
                    type: 'bar',
                    barWidth: '30%',
                    itemStyle: {
                        normal: {
                            color: function (params) {
                                // build a color map as your need.
                                var colorList = [
                                    '#B22323', '#83CEF1', '#6E7370', '#7E4894',
                                    '#304392', '#00FFFF', '#FF8463', '#f39c11'
                                ];
                                return colorList[params.dataIndex]
                            },
                            label: {
                                show: true,
                                position: 'top',
                                // formatter: '{b}\n{c}%',　　　
                            }
                        }
                    },
                    data: companyRatio
                }
            ]
        };
}`

**Comment by superandrew213** [comment]
Do you have latest version installed? I released a new version 4 days ago.

Also make sure you did this:
```
Copy ./node_modules/react-native-charting/src/components/Echarts/echart.html to ./android/app/src/main/assets/.

Don't remove ./node_modules/react-native-charting/src/components/Echarts/echart.html.
```

**Comment by done134** [comment]
> Do you have latest version installed? I released a new version 4 days ago.
> 
> Also make sure you did this:
> 
> ```
> Copy ./node_modules/react-native-charting/src/components/Echarts/echart.html to ./android/app/src/main/assets/.
> 
> Don't remove ./node_modules/react-native-charting/src/components/Echarts/echart.html.
> ```

i'm sure i have install the latest version,and i have copy the echart.html to assets/.   
and my another charts is ok, so it is bother me

**Comment by done134** [comment]
> Do you have latest version installed? I released a new version 4 days ago.
> 
> Also make sure you did this:
> 
> ```
> Copy ./node_modules/react-native-charting/src/components/Echarts/echart.html to ./android/app/src/main/assets/.
> 
> Don't remove ./node_modules/react-native-charting/src/components/Echarts/echart.html.
> ```

After my test ,The problem is caused by **color: function**
![1537339473685](https://user-images.githubusercontent.com/11987773/45735492-9d5ba280-bc1a-11e8-8156-4564efc49fb0.jpg)
**but i still don't know how to solve it,the problem persists in the release version **

**Comment by superandrew213** [comment]
Can you try replacing it with this?

```js
color(params) {
  // build a color map as your need.
  var colorList = [
      '#B22323', '#83CEF1', '#6E7370', '#7E4894',
      '#304392', '#00FFFF', '#FF8463', '#f39c11'
  ];
  return colorList[params.dataIndex]
},
```

**Comment by done134** [comment]
> Can you try replacing it with this?
> 
> ```js
> color(params) {
>   // build a color map as your need.
>   var colorList = [
>       '#B22323', '#83CEF1', '#6E7370', '#7E4894',
>       '#304392', '#00FFFF', '#FF8463', '#f39c11'
>   ];
>   return colorList[params.dataIndex]
> },
> ```

I have tried this，still not work ，and i found that someone has the same problem
[https://github.com/somonus/react-native-echarts/issues/34](url)

**Comment by done134** [comment]
[https://github.com/somonus/react-native-echarts/issues/34#issuecomment-286364424](url)
I solved this problem with this solution, thank you for your help.
